remote_theme: pages-themes/slate@v0.2.0
plugins:
    - jekyll-remote-theme
show_downloads: false

title: Dyslexia
author:
    name: Santiago, with collaboration from Victor Widell
baseurl: "/dyslexia"
production_url: "https://SantiagoColla.github.io"

future: true
